project:
  type: website

website:
  title: "Wilson N. Merrell"
  page-navigation: false
  navbar:
    background: white
    foreground: dark
    logo-alt: "Wilson N. Merrell"
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching-mentoring.qmd
        text: Teaching & Mentoring
    right:
      - text: "Bluesky"
        href: https://bsky.app/profile/wilsonmerrell.bsky.social

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    include-after-body:
      text: |
        <script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>
        <script data-goatcounter="https://wilsonmerrell.goatcounter.com/count"
                async src="//gc.zgo.at/count.js"></script>
